version: '3.9'

volumes:
  postgres_db:                                 # <- Rename "volume_name"
    name: postgres_db   

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    container_name: postgres
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    volumes:
      - postgres_db:/var/lib/postgresql/data
